/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cllc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cllc.pb-c.h"
void   cllc_associated_devices__init
                     (CllcAssociatedDevices         *message)
{
  static CllcAssociatedDevices init_value = CLLC_ASSOCIATED_DEVICES__INIT;
  *message = init_value;
}
size_t cllc_associated_devices__get_packed_size
                     (const CllcAssociatedDevices *message)
{
  assert(message->base.descriptor == &cllc_associated_devices__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cllc_associated_devices__pack
                     (const CllcAssociatedDevices *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cllc_associated_devices__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cllc_associated_devices__pack_to_buffer
                     (const CllcAssociatedDevices *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cllc_associated_devices__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CllcAssociatedDevices *
       cllc_associated_devices__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CllcAssociatedDevices *)
     protobuf_c_message_unpack (&cllc_associated_devices__descriptor,
                                allocator, len, data);
}
void   cllc_associated_devices__free_unpacked
                     (CllcAssociatedDevices *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cllc_associated_devices__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cllc_statistics__init
                     (CllcStatistics         *message)
{
  static CllcStatistics init_value = CLLC_STATISTICS__INIT;
  *message = init_value;
}
size_t cllc_statistics__get_packed_size
                     (const CllcStatistics *message)
{
  assert(message->base.descriptor == &cllc_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cllc_statistics__pack
                     (const CllcStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cllc_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cllc_statistics__pack_to_buffer
                     (const CllcStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cllc_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CllcStatistics *
       cllc_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CllcStatistics *)
     protobuf_c_message_unpack (&cllc_statistics__descriptor,
                                allocator, len, data);
}
void   cllc_statistics__free_unpacked
                     (CllcStatistics *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cllc_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cllc_associated_devices__field_descriptors[4] =
{
  {
    "shortAddr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CllcAssociatedDevices, shortaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CllcAssociatedDevices, capinfo),
    &api_mac_capability_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(CllcAssociatedDevices, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CllcAssociatedDevices, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cllc_associated_devices__field_indices_by_name[] = {
  1,   /* field[1] = capInfo */
  2,   /* field[2] = rssi */
  0,   /* field[0] = shortAddr */
  3,   /* field[3] = status */
};
static const ProtobufCIntRange cllc_associated_devices__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cllc_associated_devices__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Cllc_associated_devices",
  "CllcAssociatedDevices",
  "CllcAssociatedDevices",
  "",
  sizeof(CllcAssociatedDevices),
  4,
  cllc_associated_devices__field_descriptors,
  cllc_associated_devices__field_indices_by_name,
  1,  cllc_associated_devices__number_ranges,
  (ProtobufCMessageInit) cllc_associated_devices__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cllc_statistics__field_descriptors[5] =
{
  {
    "fhNumPASolicitReceived",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CllcStatistics, fhnumpasolicitreceived),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fhNumPASent",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CllcStatistics, fhnumpasent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fhNumPANConfigSolicitsReceived",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CllcStatistics, fhnumpanconfigsolicitsreceived),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fhNumPANConfigSent",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CllcStatistics, fhnumpanconfigsent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "otherStats",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CllcStatistics, otherstats),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cllc_statistics__field_indices_by_name[] = {
  3,   /* field[3] = fhNumPANConfigSent */
  2,   /* field[2] = fhNumPANConfigSolicitsReceived */
  1,   /* field[1] = fhNumPASent */
  0,   /* field[0] = fhNumPASolicitReceived */
  4,   /* field[4] = otherStats */
};
static const ProtobufCIntRange cllc_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor cllc_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Cllc_statistics",
  "CllcStatistics",
  "CllcStatistics",
  "",
  sizeof(CllcStatistics),
  5,
  cllc_statistics__field_descriptors,
  cllc_statistics__field_indices_by_name,
  1,  cllc_statistics__number_ranges,
  (ProtobufCMessageInit) cllc_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cllc_states__enum_values_by_number[7] =
{
  { "Cllc_states_initWaiting", "CLLC_STATES__Cllc_states_initWaiting", 1 },
  { "Cllc_states_startingCoordinator", "CLLC_STATES__Cllc_states_startingCoordinator", 2 },
  { "Cllc_states_initRestoringCoordinator", "CLLC_STATES__Cllc_states_initRestoringCoordinator", 3 },
  { "Cllc_states_started", "CLLC_STATES__Cllc_states_started", 4 },
  { "Cllc_states_restored", "CLLC_STATES__Cllc_states_restored", 5 },
  { "Cllc_states_joiningAllowed", "CLLC_STATES__Cllc_states_joiningAllowed", 6 },
  { "Cllc_states_joiningNotAllowed", "CLLC_STATES__Cllc_states_joiningNotAllowed", 7 },
};
static const ProtobufCIntRange cllc_states__value_ranges[] = {
{1, 0},{0, 7}
};
static const ProtobufCEnumValueIndex cllc_states__enum_values_by_name[7] =
{
  { "Cllc_states_initRestoringCoordinator", 2 },
  { "Cllc_states_initWaiting", 0 },
  { "Cllc_states_joiningAllowed", 5 },
  { "Cllc_states_joiningNotAllowed", 6 },
  { "Cllc_states_restored", 4 },
  { "Cllc_states_started", 3 },
  { "Cllc_states_startingCoordinator", 1 },
};
const ProtobufCEnumDescriptor cllc_states__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Cllc_states",
  "Cllc_states",
  "CllcStates",
  "",
  7,
  cllc_states__enum_values_by_number,
  7,
  cllc_states__enum_values_by_name,
  1,
  cllc_states__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue cllc_coord_states__enum_values_by_number[5] =
{
  { "Cllc_coordStates_initialized", "CLLC_COORD_STATES__Cllc_coordStates_initialized", 0 },
  { "Cllc_coordStates_scanActive", "CLLC_COORD_STATES__Cllc_coordStates_scanActive", 1 },
  { "Cllc_coordStates_scanActiveCnf", "CLLC_COORD_STATES__Cllc_coordStates_scanActiveCnf", 2 },
  { "Cllc_coordStates_scanEdCnf", "CLLC_COORD_STATES__Cllc_coordStates_scanEdCnf", 3 },
  { "Cllc_coordStates_startCnf", "CLLC_COORD_STATES__Cllc_coordStates_startCnf", 4 },
};
static const ProtobufCIntRange cllc_coord_states__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex cllc_coord_states__enum_values_by_name[5] =
{
  { "Cllc_coordStates_initialized", 0 },
  { "Cllc_coordStates_scanActive", 1 },
  { "Cllc_coordStates_scanActiveCnf", 2 },
  { "Cllc_coordStates_scanEdCnf", 3 },
  { "Cllc_coordStates_startCnf", 4 },
};
const ProtobufCEnumDescriptor cllc_coord_states__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Cllc_coord_states",
  "Cllc_coord_states",
  "CllcCoordStates",
  "",
  5,
  cllc_coord_states__enum_values_by_number,
  5,
  cllc_coord_states__enum_values_by_name,
  1,
  cllc_coord_states__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
