/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: csf.proto */

#ifndef PROTOBUF_C_csf_2eproto__INCLUDED
#define PROTOBUF_C_csf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "api_mac.pb-c.h"

typedef struct _CsfDeviceInformation CsfDeviceInformation;


/* --- enums --- */


/* --- messages --- */

/*
 *! for use by web interface 
 */
struct  _CsfDeviceInformation
{
  ProtobufCMessage base;
  ApiMacDeviceDescriptor *devinfo;
  ApiMacCapabilityInfo *capinfo;
};
#define CSF_DEVICE_INFORMATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&csf_device_information__descriptor) \
    , NULL, NULL }


/* CsfDeviceInformation methods */
void   csf_device_information__init
                     (CsfDeviceInformation         *message);
size_t csf_device_information__get_packed_size
                     (const CsfDeviceInformation   *message);
size_t csf_device_information__pack
                     (const CsfDeviceInformation   *message,
                      uint8_t             *out);
size_t csf_device_information__pack_to_buffer
                     (const CsfDeviceInformation   *message,
                      ProtobufCBuffer     *buffer);
CsfDeviceInformation *
       csf_device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   csf_device_information__free_unpacked
                     (CsfDeviceInformation *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CsfDeviceInformation_Closure)
                 (const CsfDeviceInformation *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor csf_device_information__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_csf_2eproto__INCLUDED */
