/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: csf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "csf.pb-c.h"
void   csf_device_information__init
                     (CsfDeviceInformation         *message)
{
  static CsfDeviceInformation init_value = CSF_DEVICE_INFORMATION__INIT;
  *message = init_value;
}
size_t csf_device_information__get_packed_size
                     (const CsfDeviceInformation *message)
{
  assert(message->base.descriptor == &csf_device_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t csf_device_information__pack
                     (const CsfDeviceInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &csf_device_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t csf_device_information__pack_to_buffer
                     (const CsfDeviceInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &csf_device_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CsfDeviceInformation *
       csf_device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CsfDeviceInformation *)
     protobuf_c_message_unpack (&csf_device_information__descriptor,
                                allocator, len, data);
}
void   csf_device_information__free_unpacked
                     (CsfDeviceInformation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &csf_device_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor csf_device_information__field_descriptors[2] =
{
  {
    "devInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CsfDeviceInformation, devinfo),
    &api_mac_device_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CsfDeviceInformation, capinfo),
    &api_mac_capability_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned csf_device_information__field_indices_by_name[] = {
  1,   /* field[1] = capInfo */
  0,   /* field[0] = devInfo */
};
static const ProtobufCIntRange csf_device_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor csf_device_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Csf_deviceInformation",
  "CsfDeviceInformation",
  "CsfDeviceInformation",
  "",
  sizeof(CsfDeviceInformation),
  2,
  csf_device_information__field_descriptors,
  csf_device_information__field_indices_by_name,
  1,  csf_device_information__number_ranges,
  (ProtobufCMessageInit) csf_device_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
